//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Treemapolis {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Res() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Treemapolis.Res", typeof(Res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        internal static string AntialiasOff {
            get {
                return ResourceManager.GetString("AntialiasOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSAA {0}x.
        /// </summary>
        internal static string AntialiasSamples {
            get {
                return ResourceManager.GetString("AntialiasSamples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back (Alt+Left).
        /// </summary>
        internal static string CaptionBack {
            get {
                return ResourceManager.GetString("CaptionBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string CaptionClose {
            get {
                return ResourceManager.GetString("CaptionClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color files by type or by last change (C).
        /// </summary>
        internal static string CaptionColorMode {
            get {
                return ResourceManager.GetString("CaptionColorMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart as administrator (F2), drives are then read from their master file table.
        /// </summary>
        internal static string CaptionElevate {
            get {
                return ResourceManager.GetString("CaptionElevate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running as administrator, drives are read from their master file table.
        /// </summary>
        internal static string CaptionElevated {
            get {
                return ResourceManager.GetString("CaptionElevated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit full screen (Alt+Enter).
        /// </summary>
        internal static string CaptionExitFullScreen {
            get {
                return ResourceManager.GetString("CaptionExitFullScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forward (Alt+Right).
        /// </summary>
        internal static string CaptionForward {
            get {
                return ResourceManager.GetString("CaptionForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show the whole map (Home).
        /// </summary>
        internal static string CaptionFrameAll {
            get {
                return ResourceManager.GetString("CaptionFrameAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide hidden items (H).
        /// </summary>
        internal static string CaptionHideHidden {
            get {
                return ResourceManager.GetString("CaptionHideHidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximize.
        /// </summary>
        internal static string CaptionMaximize {
            get {
                return ResourceManager.GetString("CaptionMaximize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize.
        /// </summary>
        internal static string CaptionMinimize {
            get {
                return ResourceManager.GetString("CaptionMinimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore down.
        /// </summary>
        internal static string CaptionRestore {
            get {
                return ResourceManager.GetString("CaptionRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show in File Explorer.
        /// </summary>
        internal static string CaptionReveal {
            get {
                return ResourceManager.GetString("CaptionReveal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string CaptionSettings {
            get {
                return ResourceManager.GetString("CaptionSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show hidden items (H).
        /// </summary>
        internal static string CaptionShowHidden {
            get {
                return ResourceManager.GetString("CaptionShowHidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up one level (Backspace).
        /// </summary>
        internal static string CaptionUp {
            get {
                return ResourceManager.GetString("CaptionUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By last change.
        /// </summary>
        internal static string ColorModeAge {
            get {
                return ResourceManager.GetString("ColorModeAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By type.
        /// </summary>
        internal static string ColorModeType {
            get {
                return ResourceManager.GetString("ColorModeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} descriptor heap is full, it holds {1} descriptors..
        /// </summary>
        internal static string DescriptorHeapFull {
            get {
                return ResourceManager.GetString("DescriptorHeapFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cartoon.
        /// </summary>
        internal static string EffectCartoon {
            get {
                return ResourceManager.GetString("EffectCartoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neon.
        /// </summary>
        internal static string EffectNeon {
            get {
                return ResourceManager.GetString("EffectNeon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New York 2027.
        /// </summary>
        internal static string EffectNewYork {
            get {
                return ResourceManager.GetString("EffectNewYork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string EffectNone {
            get {
                return ResourceManager.GetString("EffectNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pixel art.
        /// </summary>
        internal static string EffectPixelArt {
            get {
                return ResourceManager.GetString("EffectPixelArt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0} %.
        /// </summary>
        internal static string ElevationPercent {
            get {
                return ResourceManager.GetString("ElevationPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid.
        /// </summary>
        internal static string GroundGrid {
            get {
                return ResourceManager.GetString("GroundGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string GroundNone {
            get {
                return ResourceManager.GetString("GroundNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plain.
        /// </summary>
        internal static string GroundPlain {
            get {
                return ResourceManager.GetString("GroundPlain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, shader model {1}, ray tracing {2}, mesh shaders {3}.
        /// </summary>
        internal static string HudAdapter {
            get {
                return ResourceManager.GetString("HudAdapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  › .
        /// </summary>
        internal static string HudBreadcrumbSeparator {
            get {
                return ResourceManager.GetString("HudBreadcrumbSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0} fps, CPU {1:0.00} ms per frame.
        /// </summary>
        internal static string HudFrame {
            get {
                return ResourceManager.GetString("HudFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPU {0}.
        /// </summary>
        internal static string HudGpu {
            get {
                return ResourceManager.GetString("HudGpu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:N0} instances, {1:N0} drawn, {2:N0} labels.
        /// </summary>
        internal static string HudInstances {
            get {
                return ResourceManager.GetString("HudInstances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:N0} items, {1}.
        /// </summary>
        internal static string HudItems {
            get {
                return ResourceManager.GetString("HudItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout {0:0} ms, {1:N0} folders, {2:N0} files, video memory {3:N0} MB.
        /// </summary>
        internal static string HudLayout {
            get {
                return ResourceManager.GetString("HudLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to read from the master file table of {0}.
        /// </summary>
        internal static string HudMasterFileTableRead {
            get {
                return ResourceManager.GetString("HudMasterFileTableRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reading the master file table of {0}, {1:N0} of {2:N0} records.
        /// </summary>
        internal static string HudMasterFileTableReading {
            get {
                return ResourceManager.GetString("HudMasterFileTableReading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not supported.
        /// </summary>
        internal static string HudNotSupported {
            get {
                return ResourceManager.GetString("HudNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1:0.00} ms.
        /// </summary>
        internal static string HudPass {
            get {
                return ResourceManager.GetString("HudPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSAA {0}x.
        /// </summary>
        internal static string HudSamples {
            get {
                return ResourceManager.GetString("HudSamples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the scan stopped, {0}.
        /// </summary>
        internal static string HudScanError {
            get {
                return ResourceManager.GetString("HudScanError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning, {0:N0} items, {1:N0} per second, {2}.
        /// </summary>
        internal static string HudScanning {
            get {
                return ResourceManager.GetString("HudScanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} walked folder by folder.
        /// </summary>
        internal static string HudWalked {
            get {
                return ResourceManager.GetString("HudWalked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} free of {1}.
        /// </summary>
        internal static string IslandDriveDetail {
            get {
                return ResourceManager.GetString("IslandDriveDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Within a day.
        /// </summary>
        internal static string LegendAgeDay {
            get {
                return ResourceManager.GetString("LegendAgeDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Within a month.
        /// </summary>
        internal static string LegendAgeMonth {
            get {
                return ResourceManager.GetString("LegendAgeMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Older.
        /// </summary>
        internal static string LegendAgeOlder {
            get {
                return ResourceManager.GetString("LegendAgeOlder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Within three years.
        /// </summary>
        internal static string LegendAgeThreeYears {
            get {
                return ResourceManager.GetString("LegendAgeThreeYears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Within a week.
        /// </summary>
        internal static string LegendAgeWeek {
            get {
                return ResourceManager.GetString("LegendAgeWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Within a year.
        /// </summary>
        internal static string LegendAgeYear {
            get {
                return ResourceManager.GetString("LegendAgeYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smaller items grouped.
        /// </summary>
        internal static string LegendAggregate {
            get {
                return ResourceManager.GetString("LegendAggregate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archives and disk images.
        /// </summary>
        internal static string LegendArchives {
            get {
                return ResourceManager.GetString("LegendArchives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio.
        /// </summary>
        internal static string LegendAudio {
            get {
                return ResourceManager.GetString("LegendAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code and text formats.
        /// </summary>
        internal static string LegendCode {
            get {
                return ResourceManager.GetString("LegendCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents.
        /// </summary>
        internal static string LegendDocuments {
            get {
                return ResourceManager.GetString("LegendDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drives.
        /// </summary>
        internal static string LegendDrives {
            get {
                return ResourceManager.GetString("LegendDrives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folders, lighter when deeper.
        /// </summary>
        internal static string LegendFolders {
            get {
                return ResourceManager.GetString("LegendFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hidden and system items are darker.
        /// </summary>
        internal static string LegendHidden {
            get {
                return ResourceManager.GetString("LegendHidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images.
        /// </summary>
        internal static string LegendImages {
            get {
                return ResourceManager.GetString("LegendImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No extension.
        /// </summary>
        internal static string LegendNoExtension {
            get {
                return ResourceManager.GetString("LegendNoExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other types, one color each.
        /// </summary>
        internal static string LegendOtherTypes {
            get {
                return ResourceManager.GetString("LegendOtherTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programs and libraries.
        /// </summary>
        internal static string LegendPrograms {
            get {
                return ResourceManager.GetString("LegendPrograms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files by last change.
        /// </summary>
        internal static string LegendTitleAge {
            get {
                return ResourceManager.GetString("LegendTitleAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files by type.
        /// </summary>
        internal static string LegendTitleType {
            get {
                return ResourceManager.GetString("LegendTitleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video.
        /// </summary>
        internal static string LegendVideo {
            get {
                return ResourceManager.GetString("LegendVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading the master file table of {0}.
        /// </summary>
        internal static string LoadingMasterFileTable {
            get {
                return ResourceManager.GetString("LoadingMasterFileTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:N0} of {1:N0} records.
        /// </summary>
        internal static string LoadingRecords {
            get {
                return ResourceManager.GetString("LoadingRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning {0}.
        /// </summary>
        internal static string LoadingScanning {
            get {
                return ResourceManager.GetString("LoadingScanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The location could not be found from its identifier list..
        /// </summary>
        internal static string LocationIdListNotFound {
            get {
                return ResourceManager.GetString("LocationIdListNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The location '{0}' could not be found..
        /// </summary>
        internal static string LocationNotFound {
            get {
                return ResourceManager.GetString("LocationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acrylic.
        /// </summary>
        internal static string MaterialAcrylic {
            get {
                return ResourceManager.GetString("MaterialAcrylic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mica.
        /// </summary>
        internal static string MaterialMica {
            get {
                return ResourceManager.GetString("MaterialMica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string MaterialNone {
            get {
                return ResourceManager.GetString("MaterialNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animate.
        /// </summary>
        internal static string PassAnimate {
            get {
                return ResourceManager.GetString("PassAnimate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cull.
        /// </summary>
        internal static string PassCull {
            get {
                return ResourceManager.GetString("PassCull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw.
        /// </summary>
        internal static string PassDraw {
            get {
                return ResourceManager.GetString("PassDraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effect.
        /// </summary>
        internal static string PassEffect {
            get {
                return ResourceManager.GetString("PassEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Labels.
        /// </summary>
        internal static string PassLabels {
            get {
                return ResourceManager.GetString("PassLabels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shadows.
        /// </summary>
        internal static string PassShadows {
            get {
                return ResourceManager.GetString("PassShadows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        internal static string PassUpload {
            get {
                return ResourceManager.GetString("PassUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear the list.
        /// </summary>
        internal static string RecentClear {
            get {
                return ResourceManager.GetString("RecentClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing yet.
        /// </summary>
        internal static string RecentNothing {
            get {
                return ResourceManager.GetString("RecentNothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove the ones that are gone.
        /// </summary>
        internal static string RecentRemoveMissing {
            get {
                return ResourceManager.GetString("RecentRemoveMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antialiasing.
        /// </summary>
        internal static string SettingAntialias {
            get {
                return ResourceManager.GetString("SettingAntialias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colors.
        /// </summary>
        internal static string SettingColors {
            get {
                return ResourceManager.GetString("SettingColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effect (E).
        /// </summary>
        internal static string SettingEffect {
            get {
                return ResourceManager.GetString("SettingEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building height.
        /// </summary>
        internal static string SettingElevation {
            get {
                return ResourceManager.GetString("SettingElevation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show the settings file.
        /// </summary>
        internal static string SettingFile {
            get {
                return ResourceManager.GetString("SettingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ground.
        /// </summary>
        internal static string SettingGround {
            get {
                return ResourceManager.GetString("SettingGround", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window material.
        /// </summary>
        internal static string SettingMaterial {
            get {
                return ResourceManager.GetString("SettingMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent folders.
        /// </summary>
        internal static string SettingRecentFolders {
            get {
                return ResourceManager.GetString("SettingRecentFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan every drive in the background.
        /// </summary>
        internal static string SettingScanDrives {
            get {
                return ResourceManager.GetString("SettingScanDrives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show hidden items.
        /// </summary>
        internal static string SettingShowHidden {
            get {
                return ResourceManager.GetString("SettingShowHidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show drives and places.
        /// </summary>
        internal static string SettingShowIsland {
            get {
                return ResourceManager.GetString("SettingShowIsland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show names.
        /// </summary>
        internal static string SettingShowLabels {
            get {
                return ResourceManager.GetString("SettingShowLabels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show color legend.
        /// </summary>
        internal static string SettingShowLegend {
            get {
                return ResourceManager.GetString("SettingShowLegend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show performance.
        /// </summary>
        internal static string SettingShowPerformance {
            get {
                return ResourceManager.GetString("SettingShowPerformance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show shadows.
        /// </summary>
        internal static string SettingShowShadows {
            get {
                return ResourceManager.GetString("SettingShowShadows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show item count and scan.
        /// </summary>
        internal static string SettingShowStatus {
            get {
                return ResourceManager.GetString("SettingShowStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show thumbnails.
        /// </summary>
        internal static string SettingShowThumbnails {
            get {
                return ResourceManager.GetString("SettingShowThumbnails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sun direction.
        /// </summary>
        internal static string SettingSunAngle {
            get {
                return ResourceManager.GetString("SettingSunAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        internal static string SettingTheme {
            get {
                return ResourceManager.GetString("SettingTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thumbnails from.
        /// </summary>
        internal static string SettingThumbnailPixels {
            get {
                return ResourceManager.GetString("SettingThumbnailPixels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical sync.
        /// </summary>
        internal static string SettingVSync {
            get {
                return ResourceManager.GetString("SettingVSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show changes as they happen.
        /// </summary>
        internal static string SettingWatchChanges {
            get {
                return ResourceManager.GetString("SettingWatchChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The shader '{0}' is not embedded in the executable..
        /// </summary>
        internal static string ShaderNotFound {
            get {
                return ResourceManager.GetString("ShaderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0}°.
        /// </summary>
        internal static string SunAngleDegrees {
            get {
                return ResourceManager.GetString("SunAngleDegrees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File .
        /// </summary>
        internal static string SyntheticFilePrefix {
            get {
                return ResourceManager.GetString("SyntheticFilePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder .
        /// </summary>
        internal static string SyntheticFolderPrefix {
            get {
                return ResourceManager.GetString("SyntheticFolderPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synthetic disk.
        /// </summary>
        internal static string SyntheticRootName {
            get {
                return ResourceManager.GetString("SyntheticRootName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        internal static string ThemeDark {
            get {
                return ResourceManager.GetString("ThemeDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        internal static string ThemeLight {
            get {
                return ResourceManager.GetString("ThemeLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        internal static string ThemeSystem {
            get {
                return ResourceManager.GetString("ThemeSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} px on screen.
        /// </summary>
        internal static string ThumbnailPixels {
            get {
                return ResourceManager.GetString("ThumbnailPixels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        internal static string TooltipAggregate {
            get {
                return ResourceManager.GetString("TooltipAggregate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        internal static string TooltipContainer {
            get {
                return ResourceManager.GetString("TooltipContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        internal static string TooltipDrive {
            get {
                return ResourceManager.GetString("TooltipDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        internal static string TooltipFile {
            get {
                return ResourceManager.GetString("TooltipFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        internal static string TooltipFileWithoutDate {
            get {
                return ResourceManager.GetString("TooltipFileWithoutDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        internal static string TooltipPlace {
            get {
                return ResourceManager.GetString("TooltipPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treemapolis.
        /// </summary>
        internal static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, the graphics device was lost ({1}).
        /// </summary>
        internal static string WindowTitleDeviceLost {
            get {
                return ResourceManager.GetString("WindowTitleDeviceLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ({1:0} fps on {2}, {3:N0} items, {4:N0} drawn).
        /// </summary>
        internal static string WindowTitleStatistics {
            get {
                return ResourceManager.GetString("WindowTitleStatistics", resourceCulture);
            }
        }
    }
}
